#!/bin/sh
#
# This file is interpreted as shell script.
# Put your custom mwan3 action here, they will
# be executed with each netifd hotplug interface event
# on interfaces for which mwan3 is enabled.
#
# There are three main environment variables that are passed to this script.
#
# $ACTION
#      <ifup>         Is called by netifd and mwan3track
#      <ifdown>       Is called by netifd and mwan3track
#      <connected>    Is only called by mwan3track if tracking was successful
#      <disconnected> Is only called by mwan3track if tracking has failed
# $INTERFACE    Name of the interface which went up or down (e.g. "wan" or "wwan")
# $DEVICE       Physical device name which interface went up or down (e.g. "eth0" or "wwan0")

logger -t mwan3-hotplug-openvpn "Got hotplug event $ACTION"

case "$ACTION" in
        connected)
                logger -t mwan3-hotplug-openvpn "Received action $ACTION for $INTERFACE ($DEVICE)."
                if [ "$INTERFACE" = wana -o "$INTERFACE" = wanb ]
                then
                        logger -t mwan3-hotplug-openvpn "Getting list of OpenVPN tunnels preferring $INTERFACE."
                        for instance in `uci get hopcloud.ovpnaffinity.$INTERFACE`
                        do
                                if [ -n "$instance" ]
                                then
                                        logger -t mwan3-hotplug-openvpn "Restarting $instance"
                                        /etc/init.d/openvpn restart $instance
                                fi
                        done
                fi
        ;;

        disconnected)
                logger -t mwan3-hotplug-openvpn "Received action $ACTION for $INTERFACE ($DEVICE)."
        ;;

esac

exit 0

